lev:
  ssl:
    publicCertificate: ${LEV_PUBLIC_CERTIFICATE:}
    privateKey: ${LEV_PRIVATE_KEY:}
  bearertoken:
    accessTokenUri: ${LEV_ACCESS_TOKEN_URI:}
    clientId: ${LEV_CLIENT_ID:}
    clientSecret: ${LEV_CLIENT_SECRET:}
    username: ${LEV_USERNAME:}
    password: ${LEV_PASSWORD:}
  death:
    url: ${LEV_DEATH_URL:}


