/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package uk.gov.hmcts.lifeevents.client.api;

import uk.gov.hmcts.lifeevents.client.model.GeneralError;
import java.time.LocalDate;
import uk.gov.hmcts.lifeevents.client.model.V01Birth;
import uk.gov.hmcts.lifeevents.client.model.V0Birth;
import uk.gov.hmcts.lifeevents.client.model.V1Birth;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-03-02T13:36:51.963195Z[Europe/London]")

@Validated
@Api(value = "Birth", description = "the Birth API")
public interface BirthApi {

    /**
     * GET /api/v0/events/birth/{systemNumber} : Look up a specific birth record
     * Look up individual birth records using the &#x60;systemNumber&#x60; printed in the bottom-left of the birth certificate.
     *
     * @param systemNumber The system number printed in the bottom-left of the birth certificate (required)
     * @return successful operation (status code 200)
     *         or Resource not found (status code 404)
     *         or Bad request (status code 200)
     */
    @ApiOperation(value = "Look up a specific birth record", nickname = "readBirth", notes = "Look up individual birth records using the `systemNumber` printed in the bottom-left of the birth certificate.", response = V0Birth.class, authorizations = {
        @Authorization(value = "bearerToken", scopes = {
            
            })
    }, tags={ "birth","v0", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = V0Birth.class),
        @ApiResponse(code = 404, message = "Resource not found", response = GeneralError.class),
        @ApiResponse(code = 200, message = "Bad request", response = GeneralError.class) })
    @RequestMapping(value = "/api/v0/events/birth/{systemNumber}",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<V0Birth> readBirth(@ApiParam(value = "The system number printed in the bottom-left of the birth certificate",required=true) @PathVariable("systemNumber") Integer systemNumber);


    /**
     * GET /api/v0.1/events/birth/{systemNumber} : Look up a specific birth record (returns &#x60;null&#x60; for fields that are not on the birth certificate)
     * Look up individual birth records using the &#x60;systemNumber&#x60; printed in the bottom-left of the birth certificate.
     *
     * @param systemNumber The system number printed in the bottom-left of the birth certificate (required)
     * @return successful operation (status code 200)
     *         or Resource not found (status code 404)
     *         or Bad request (status code 200)
     */
    @ApiOperation(value = "Look up a specific birth record (returns `null` for fields that are not on the birth certificate)", nickname = "readBirth_0", notes = "Look up individual birth records using the `systemNumber` printed in the bottom-left of the birth certificate.", response = V01Birth.class, authorizations = {
        @Authorization(value = "bearerToken", scopes = {
            
            })
    }, tags={ "birth","v0.1", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = V01Birth.class),
        @ApiResponse(code = 404, message = "Resource not found", response = GeneralError.class),
        @ApiResponse(code = 200, message = "Bad request", response = GeneralError.class) })
    @RequestMapping(value = "/api/v0.1/events/birth/{systemNumber}",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<V01Birth> readBirth_0(@ApiParam(value = "The system number printed in the bottom-left of the birth certificate",required=true) @PathVariable("systemNumber") Integer systemNumber);


    /**
     * GET /v1/registration/birth/{id} : Look up a specific birth record
     * Look up individual birth records using the &#x60;systemNumber&#x60; printed in the bottom-left of the birth certificate. (UNSTABLE: This endpoint is subject to change.)
     *
     * @param id The system number printed in the bottom-left of the birth certificate (required)
     * @return successful operation (status code 200)
     *         or Resource not found (status code 404)
     *         or Bad request (status code 200)
     */
    @ApiOperation(value = "Look up a specific birth record", nickname = "readV1Birth", notes = "Look up individual birth records using the `systemNumber` printed in the bottom-left of the birth certificate. (UNSTABLE: This endpoint is subject to change.)", response = V1Birth.class, authorizations = {
        @Authorization(value = "bearerToken", scopes = {
            
            })
    }, tags={ "birth","v1","unstable", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = V1Birth.class),
        @ApiResponse(code = 404, message = "Resource not found", response = GeneralError.class),
        @ApiResponse(code = 200, message = "Bad request", response = GeneralError.class) })
    @RequestMapping(value = "/v1/registration/birth/{id}",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<V1Birth> readV1Birth(@ApiParam(value = "The system number printed in the bottom-left of the birth certificate",required=true) @PathVariable("id") Integer id);


    /**
     * GET /api/v0/events/birth : Search for birth records
     * Search for birth records by supplying the date of birth, surname and at least the first forename of the child.
     *
     * @param forenames The child&#39;s forenames. The first name must be provided but middlenames are optional. (required)
     * @param lastname The child&#39;s surname. (required)
     * @param dateofbirth The child&#39;s date of birth in international format. (required)
     * @return successful operation (status code 200)
     *         or Bad request (status code 200)
     */
    @ApiOperation(value = "Search for birth records", nickname = "searchBirth", notes = "Search for birth records by supplying the date of birth, surname and at least the first forename of the child.", response = V0Birth.class, responseContainer = "List", authorizations = {
        @Authorization(value = "bearerToken", scopes = {
            
            })
    }, tags={ "birth","v0", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = V0Birth.class, responseContainer = "List"),
        @ApiResponse(code = 200, message = "Bad request", response = GeneralError.class) })
    @RequestMapping(value = "/api/v0/events/birth",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<List<V0Birth>> searchBirth(@NotNull @ApiParam(value = "The child's forenames. The first name must be provided but middlenames are optional.", required = true) @Valid @RequestParam(value = "forenames", required = true) String forenames,@NotNull @ApiParam(value = "The child's surname.", required = true) @Valid @RequestParam(value = "lastname", required = true) String lastname,@NotNull @ApiParam(value = "The child's date of birth in international format.", required = true) @Valid @RequestParam(value = "dateofbirth", required = true) @org.springframework.format.annotation.DateTimeFormat(iso = org.springframework.format.annotation.DateTimeFormat.ISO.DATE) LocalDate dateofbirth);


    /**
     * GET /api/v0.1/events/birth : Search for birth records (returns &#x60;null&#x60; for fields that are not on the birth certificate)
     * Search for birth records by supplying the date of birth, surname and at least the first forename of the child.
     *
     * @param forenames The child&#39;s forenames. The first name must be provided but middlenames are optional. (required)
     * @param lastname The child&#39;s surname. (required)
     * @param dateofbirth The child&#39;s date of birth in international format. (required)
     * @return successful operation (status code 200)
     *         or Bad request (status code 200)
     */
    @ApiOperation(value = "Search for birth records (returns `null` for fields that are not on the birth certificate)", nickname = "searchBirth_0", notes = "Search for birth records by supplying the date of birth, surname and at least the first forename of the child.", response = V01Birth.class, responseContainer = "List", authorizations = {
        @Authorization(value = "bearerToken", scopes = {
            
            })
    }, tags={ "birth","v0.1", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = V01Birth.class, responseContainer = "List"),
        @ApiResponse(code = 200, message = "Bad request", response = GeneralError.class) })
    @RequestMapping(value = "/api/v0.1/events/birth",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<List<V01Birth>> searchBirth_0(@NotNull @ApiParam(value = "The child's forenames. The first name must be provided but middlenames are optional.", required = true) @Valid @RequestParam(value = "forenames", required = true) String forenames,@NotNull @ApiParam(value = "The child's surname.", required = true) @Valid @RequestParam(value = "lastname", required = true) String lastname,@NotNull @ApiParam(value = "The child's date of birth in international format.", required = true) @Valid @RequestParam(value = "dateofbirth", required = true) @org.springframework.format.annotation.DateTimeFormat(iso = org.springframework.format.annotation.DateTimeFormat.ISO.DATE) LocalDate dateofbirth);


    /**
     * GET /v1/registration/birth : Search for birth records
     * Search for birth records by supplying the date of birth, surname and at least the first forename of the child. (UNSTABLE: This endpoint is subject to change.)
     *
     * @param forenames The child&#39;s forenames. The first name must be provided but middlenames are optional. (required)
     * @param surname The child&#39;s surname. (required)
     * @param dateOfBirth The child&#39;s date of birth in international format. (required)
     * @return successful operation (status code 200)
     *         or Bad request (status code 200)
     */
    @ApiOperation(value = "Search for birth records", nickname = "searchV1Birth", notes = "Search for birth records by supplying the date of birth, surname and at least the first forename of the child. (UNSTABLE: This endpoint is subject to change.)", response = V1Birth.class, responseContainer = "List", authorizations = {
        @Authorization(value = "bearerToken", scopes = {
            
            })
    }, tags={ "birth","v1","unstable", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = V1Birth.class, responseContainer = "List"),
        @ApiResponse(code = 200, message = "Bad request", response = GeneralError.class) })
    @RequestMapping(value = "/v1/registration/birth",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<List<V1Birth>> searchV1Birth(@NotNull @ApiParam(value = "The child's forenames. The first name must be provided but middlenames are optional.", required = true) @Valid @RequestParam(value = "forenames", required = true) String forenames,@NotNull @ApiParam(value = "The child's surname.", required = true) @Valid @RequestParam(value = "surname", required = true) String surname,@NotNull @ApiParam(value = "The child's date of birth in international format.", required = true) @Valid @RequestParam(value = "dateOfBirth", required = true) @org.springframework.format.annotation.DateTimeFormat(iso = org.springframework.format.annotation.DateTimeFormat.ISO.DATE) LocalDate dateOfBirth);

}
