/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package uk.gov.hmcts.lifeevents.client.api;

import uk.gov.hmcts.lifeevents.client.model.GeneralError;
import java.time.LocalDate;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-03-02T13:36:51.963195Z[Europe/London]")

@Validated
@Api(value = "Default", description = "the Default API")
public interface DefaultApi {

    /**
     * GET /api/v0/audit/user-activity : Query user activity
     *
     * @param from The beginning of the timespan to search (optional)
     * @param to The end of the timespan to search (optional)
     * @return successful operation (status code 200)
     *         or Bad request (status code 200)
     */
    @ApiOperation(value = "Query user activity", nickname = "searchActivity", notes = "", response = Object.class, authorizations = {
        @Authorization(value = "bearerToken", scopes = {
            @AuthorizationScope(scope = "audit", description = "read audit data")
            })
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Object.class),
        @ApiResponse(code = 200, message = "Bad request", response = GeneralError.class) })
    @RequestMapping(value = "/api/v0/audit/user-activity",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<Object> searchActivity(@ApiParam(value = "The beginning of the timespan to search") @Valid @RequestParam(value = "from", required = false) @org.springframework.format.annotation.DateTimeFormat(iso = org.springframework.format.annotation.DateTimeFormat.ISO.DATE) LocalDate from,@ApiParam(value = "The end of the timespan to search") @Valid @RequestParam(value = "to", required = false) @org.springframework.format.annotation.DateTimeFormat(iso = org.springframework.format.annotation.DateTimeFormat.ISO.DATE) LocalDate to);

}
