/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package uk.gov.hmcts.lifeevents.client.api;

import uk.gov.hmcts.lifeevents.client.model.GeneralError;
import java.time.LocalDate;
import uk.gov.hmcts.lifeevents.client.model.V1Marriage;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-03-10T16:10:49.642712Z[Europe/London]")

@Validated
@Api(value = "Marriage", description = "the Marriage API")
public interface MarriageApi {

    /**
     * GET /v1/registration/marriage/{id} : Look up a specific marriage record
     * Look up individual marriage records using the &#x60;systemNumber&#x60; printed in the bottom-left of the marriage certificate. (UNSTABLE: This endpoint is subject to change.)
     *
     * @param id The system number printed in the bottom-left of the marriage certificate (required)
     * @return successful operation (status code 200)
     *         or Resource not found (status code 404)
     *         or Bad request (status code 200)
     */
    @ApiOperation(value = "Look up a specific marriage record", nickname = "readV1Marriage", notes = "Look up individual marriage records using the `systemNumber` printed in the bottom-left of the marriage certificate. (UNSTABLE: This endpoint is subject to change.)", response = V1Marriage.class, authorizations = {
        @Authorization(value = "bearerToken", scopes = {
            
            })
    }, tags={ "marriage","v1","unstable", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = V1Marriage.class),
        @ApiResponse(code = 404, message = "Resource not found", response = GeneralError.class),
        @ApiResponse(code = 200, message = "Bad request", response = GeneralError.class) })
    @RequestMapping(value = "/v1/registration/marriage/{id}",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<V1Marriage> readV1Marriage(@ApiParam(value = "The system number printed in the bottom-left of the marriage certificate",required=true) @PathVariable("id") Integer id);


    /**
     * GET /v1/registration/marriage : Search for marriage records
     * Search for marriage records by supplying the date of marriage as well as the surname and at least the first forename of one of the partners. (UNSTABLE: This endpoint is subject to change.)
     *
     * @param forenames The person&#39;s forenames. The first name must be provided but middlenames are optional. (required)
     * @param surname The person&#39;s surname. (required)
     * @param dateOfMarriage The date of the marriage in international format. (required)
     * @return successful operation (status code 200)
     *         or Bad request (status code 200)
     */
    @ApiOperation(value = "Search for marriage records", nickname = "searchV1Marriage", notes = "Search for marriage records by supplying the date of marriage as well as the surname and at least the first forename of one of the partners. (UNSTABLE: This endpoint is subject to change.)", response = V1Marriage.class, responseContainer = "List", authorizations = {
        @Authorization(value = "bearerToken", scopes = {
            
            })
    }, tags={ "marriage","v1","unstable", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = V1Marriage.class, responseContainer = "List"),
        @ApiResponse(code = 200, message = "Bad request", response = GeneralError.class) })
    @RequestMapping(value = "/v1/registration/marriage",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<List<V1Marriage>> searchV1Marriage(@NotNull @ApiParam(value = "The person's forenames. The first name must be provided but middlenames are optional.", required = true) @Valid @RequestParam(value = "forenames", required = true) String forenames,@NotNull @ApiParam(value = "The person's surname.", required = true) @Valid @RequestParam(value = "surname", required = true) String surname,@NotNull @ApiParam(value = "The date of the marriage in international format.", required = true) @Valid @RequestParam(value = "dateOfMarriage", required = true) @org.springframework.format.annotation.DateTimeFormat(iso = org.springframework.format.annotation.DateTimeFormat.ISO.DATE) LocalDate dateOfMarriage);

}
