name: Upload to Bintray

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - refs/tags/*
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./gradlew check
      - name: Integration test
        env:
          LEV_ACCESS_TOKEN_URI: ${{ secrets.ACCESS_TOKEN_URI }}
          LEV_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          LEV_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          LEV_USERNAME: ${{ secrets.USERNAME }}
          LEV_PASSWORD: ${{ secrets.PASSWORD }}
          LEV_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          LEV_PUBLIC_CERTIFICATE: ${{ secrets.PUBLIC_CERTIFICATE }}
        run: ./gradlew integration
      - name: Release
        env:
          BINTRAY_USER: jenkins-reform-hmcts
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          RELEASE_VERSION: ${{ github.ref }}
        run: ./gradlew bintrayUpload
        if: startsWith(github.ref, 'refs/tags')
